<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Faq
 */
?>
<?php
/**
 * @var \Amasty\Faq\Block\Lists\SocialShare $block
 */
?>
<div class="amfaq-social-buttons">
    <?php foreach ($block->getButtons() as $button): ?>
        <?php $label = $block->escapeHtml($button->getName()); ?>
        <a href="<?= $block->escapeUrl($block->renderButtonHref($button)) ?>"
            <?= /* @noEscape */ $block->getAttributesHtml($button) ?>>
            <img src="<?= $block->escapeUrl($block->getImage($button)); ?>"
                 alt="<?= $block->escapeHtml($label); ?>"
                 title="<?= $block->escapeHtml($label); ?>" />
        </a>
    <?php endforeach; ?>
</div>
