<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Groupcat
 */
?>
<?php

// @codingStandardsIgnoreFile

/** @var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset $block */
/** @var  \Magento\Framework\Data\Form\Element\AbstractElement $_element */
?>
<?php $_element = $block->getElement() ?>
<?php $_jsObjectName = $block->getFieldSetId() != null ? $block->getFieldSetId() : $_element->getHtmlId() ?>
<div class="rule-tree">
    <fieldset id="<?= /* @escapeNotVerified */ $_jsObjectName ?>" <?= /* @escapeNotVerified */ $_element->serialize(['class']) ?> class="fieldset">
    <?php if ($_element->getComment()): ?>
        <div class="messages">
            <div class="message message-notice"><?= $block->escapeHtml($_element->getComment()) ?></div>
        </div>
    <?php endif; ?>
    <div class="rule-tree-wrapper">
        <?= $_element->getChildrenHtml() ?>
    </div>
    </fieldset>
</div>
<script>
require([
    "Magento_Rule/rules",
    "prototype"
], function(VarienRulesForm){

window.<?= /* @escapeNotVerified */ $_jsObjectName ?> = new VarienRulesForm('<?= /* @escapeNotVerified */ $_jsObjectName ?>', '<?= /* @escapeNotVerified */ $block->getNewChildUrl() ?>');
<?php if ($_element->getReadonly()): ?>
    <?= $_element->getHtmlId() ?>.setReadonly(true);
<?php endif; ?>

});
</script>
