<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/**
 * @var $block \Amasty\Shopby\Block\Product\ProductList\Ajax
 */
if (!$block->canShowBlock()) {
    return;
}
?>
<script type="text/x-magento-init">
{
    "body.cms-index-index": {
        "amShopbyAjax": {
                "submitByClick": <?= /* @noEscape */ (int) $block->submitByClick();?>,
                "clearUrl": "<?= $block->escapeUrl($block->getClearUrl());?>",
                "isCategorySingleSelect": "<?= /* @noEscape */ $block->isCategorySingleSelect();?>"
            }
        }
}
</script>
