<?php $totalPayoutsPending = $block->getTotalPayoutsPending();
$totalReadyToPay = $block->getTotalReadyToPay();
//echo "<pre>";
//print_r($block->getPendingPayoutLastUpdated());
//die;
?>

<div>
    <div class="payout-tile">
        <div class="tile-row">
            <div class="tile-title"><strong>Total Payouts Pending</strong></div>
            <div class="tile-updated"><?php echo $block->getPendingPayoutLastUpdated() ? 'Last Updated: ' .$block->getPendingPayoutLastUpdated():''; ?></div>
        </div>
        <div class="width100p">
            <div class="tile-first-col">
                <div class="font-size-1r">Total </div>
                <div class="tile-currency"><?php echo $block->escapeHtml($block->currency($totalPayoutsPending['total_balance_owing'])); ?></div>

            </div>
            <div class="tile-2nd-col">
                <div class="font-size-1r">Net Amount </div>
                <div class="tile-currency"><?php echo $block->escapeHtml($block->currency($totalPayoutsPending['total_balance_owing_net_amount'])); ?></div>
            </div>
            <div style="float:left; width:22%">
                <div class="font-size-1r">Taxes </div>
                <div class="tile-currency"><?php echo $block->escapeHtml($block->currency($totalPayoutsPending['total_balance_owing_tax'])); ?> </div>
            </div>
        </div>

    </div>
    <div class="tile-separator">
        &nbsp;
    </div>
    <div class="payout-tile">
        <div class="tile-row">
            <div class="tile-title"><strong>Ready to Pay</strong></div>
            <div class="tile-updated"><?php echo $block->getReadyToPayLastUpdated() ? 'Last Updated: '. $block->getReadyToPayLastUpdated(): ''; ?></div>
        </div>
        <div class="width100p">
            <div class="tile-first-col">
                <div class="font-size-1r">Total </div>
                <div class="tile-currency"><?php echo $block->escapeHtml($block->currency($totalReadyToPay['total_payout_amount'])); ?></div>

            </div>
            <div class="tile-2nd-col">
                <div class="font-size-1r">Shipping Paid By Customer </div>
                <div class="tile-currency"><?php echo $block->escapeHtml($block->currency($totalReadyToPay['total_payout_shipping'])); ?></div>

            </div>
            <div class="tile-3rd-col">
                <div class="font-size-1r">Net Amount </div>
                <div class="tile-currency"><?php echo $block->escapeHtml($block->currency($totalReadyToPay['total_payout_net_amount'])); ?></div>
            </div>
            <div class="tile-4th-col">
                <div class="font-size-1r">Taxes </div>
                <div class="tile-currency"><?php echo $block->escapeHtml($block->currency($totalReadyToPay['total_payout_amount_tax'])); ?></div>
            </div>
        </div>
    </div>
</div>
