<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Faq
 */
?>
<?php
/** @var \Magento\Backend\Block\Template $block **/
?>
<div class="page-main-actions" id="faqQuestionsGrid">
    <div class="page-actions">
        <div class="page-actions-buttons">
            <button
                    type="button"
                    data-role="action"
                    onclick="'. <?= $block->escapeHtml($block->getChooserId()) ?> .'.close()">
                <span>Cancel</span>
            </button>
            <button class="action-primary" type="button" data-role="action" id="addSelectedFiles">
                <span><?= $block->escapeHtml(__('Add Selected Questions')) ?></span>
            </button>
        </div>
    </div>
</div>
