<?php
/* @var $block \Mirasvit\Rma\Block\Rma\View\Items */
?>
<table cellspacing="0" cellpadding="0" border="0" width="650">
        <thead>
            <tr>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo __("Product Name") ?></th>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo __("SKU") ?></th>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo __("Qty") ?></th>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo __("Reason") ?></th>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo __("Condition") ?></th>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo __("Resolution") ?></th>
            </tr>
        </thead>
        <tbody>
<?php
$color = '#CCCCCC';
if ($block->getRma()): //when we preview template, rma is not set
    foreach($block->getItems() as $item):
        if (!$color) {
            $color = '#CCCCCC';
        } else {
            $color = '';
        }
    ?>
			<tr>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $block->getOrderItemLabel($item) ?></td>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $block->getOrderItemSku($item) ?></td>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $item->getQtyRequested() ?></td>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $item->getReasonName() ?></td>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $item->getConditionName() ?></td>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $item->getResolutionName() ?></td>
			</tr>
<?php
endforeach;
endif;

?>
		</tbody>
</table>