<div class="nav-wrapper">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active list-item"><a class="list-anchor" href="#tab-0-0" aria-controls="New to selling overseas" role="tab" data-toggle="tab">Checklist</a></li>
        <li  class="list-item"><a class="list-anchor" href="<?php echo $this->getUrl('readinglist')?>" aria-controls="Selling overseas to Retail customers">My reading list</a></li>

    </ul>
</div>