<?php
/** @var \Mirasvit\Rma\Block\Rma\NewRma\Step2\Items $block */
?>
<div class="block">
    <div class="title">
        <div class="actions-toolbar secondary ui-add-item-button-container">
            <div class="primary">
                <button type="button" class="action secondary">
                    <span><?= __('Add Item') ?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="block-content ui-rma-items ui-offline-items-container"></div>
</div>

<div class="clearfix"></div>
