<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\Shopby\Block\Navigation\Widget\Tooltip $block */
$content = $block->getContent();
?>
<?php if ($content): ?>
    <script type="text/x-magento-init">
        {
            ".am-filter-items-<?= $block->escapeHtml($block->getFilterSetting()->getFilterCode()) ?>": {
                "amShopbyFilterAddTooltip": {
                    "content": <?= /* @noEscape */ $block->jsonEncode($content); ?>,
                    "tooltipTemplate": <?= /* @noEscape */ $block->jsonEncode($block->getTooltipTemplate()); ?>
                }
            }
        }
    </script>
<?php endif; ?>
