<div class="admin__fieldset fieldset-wrapper">
    <div class="admin__field">
        <label class="admin__field-label">
            <span>eWallet ID</span>
        </label>
        <div class="admin__field-control" >
            <div class="admin__field-note">
                <span><?php echo $block->escapeHtml($block->getVendorEwalletId());?></span>
            </div>
        </div>
    </div>
</div>