<div id="vendor-signup-wrapper">
	<!-- booking modal begins -->
	<div class="modal fade modal-full-flex has-features" tabindex="-1" role="dialog" id="vendor-signup">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close close-vendor"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Vendor Sign up</h4>
				</div>
				<div class="modal-body">
					<?php echo $this->getChildHtml('become.vendor')?>
					<div class="modal-body-flex-row">
					<?php echo $this->getChildHtml('steps.vendor')?>
						<div class="main-wrapper">
							<div class="step-container active" id="booking-step-0">
								<div class="fields-header normal">
									<h3 class="heading">Complete the form to sign up</h3>
								</div>

                                <?php echo $this->getChildHtml('sign_up.form'); ?>
                            </div>
                            <div class="step-container" id="thank-you-section">
                                <?php echo $this->getChildHtml('thanks.vendor')?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


 