<p>
    <?= __('To request a new RMA or check the status of the current RMA, please, fill out the form:')?>
</p>
<?php  ?>
<form action="<?= $block->getStep1PostUrl()?>" method="POST" data-hasrequired="<?= __('* Required Fields') ?>" data-mage-init='{"validation":{}}' class="form rma-guest-new">
    <fieldset class='fieldset'>
        <legend class="legend"><span><?= __('Order Information') ?></span></legend><br>
        <div class="field required">
            <label class="label" for="order_increment_id">
                <span><?= __('Order #') ?></span>
            </label>

            <div class="control">
                <input type='text' name="order_increment_id" id='order_increment_id' value="<?= $block->stripTags($block->getOrderIncrementId())?>" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true"/>
            </div>
        </div>
        <div class="field required">
            <label class="label" for="email">
                <span><?= __('Email') ?></span>
            </label>

            <div class="control">
                <input type='text' name="email" id='email' value="<?= $block->stripTags($block->getEmail())?>"  class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true"/>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="<?= __('Next') ?>"><span><?= __('Next') ?></span></button>
            </div>
        </div>
    </fieldset>
</form>
