<?php
/**
 * Edited for you list template
 *
 * @var $block \Smartwave\Filterproducts\Block\Home\FeaturedList
 */
$productCollection = $block->getLoadedProductCollection();
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$image = 'category_page_grid';

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
$currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode);
$currencySymbol = $currency->getCurrencySymbol();
?>

<div class="section-editedforyou">
    <div class="row" style="padding-bottom: 30px">
        <div class="col-lg-6">
            <p style="font-size: 20px; font-weight: 500; text-transform: uppercase">Edited for you</p>
        </div>
        <div class="col-lg-6">
            <a href="#" style="float: right; font-weight: 600; text-transform: uppercase">See more products</a>
        </div>
    </div>

    <div class="row">
        <?php foreach ($productCollection as $product): ?>

            <?php $productGallery = $block->getUrl('pub/media/catalog') . 'product' . $product->getData('test'); ?>

            <?php $finalPriceAmt = $product->getPriceInfo()->getPrice('final_price')->getValue(); ?>


            <div class="col-lg-3" style="padding-bottom: 30px">
                <div class="block-attribute"
                     style="background: #e5e5e5; text-align: center; position: relative; height: 100%">
                    <a href="<?php echo $product->getProductUrl() ?> ">
                        <?php $productImage = $_imagehelper->init($product, $image)->resize(340, 340); ?>
                        <?php $productImageUrl = $productImage->getUrl() ?>
                        <img src="<?php echo $productImageUrl ?>" alt="" style="width: 100%; height: 100%"/>
                    </a>
                    <div class="product-info">
                        <div class="product-item-detail"
                             style="width: 100%; padding: 10px 15px 10px 15px; font-size: 12px; line-height: 18px; height: 100%">
                            <div class="product-text-info" style="width: 60%; float: left;  text-align: left">
                                <span style="font-size: 10px; text-transform: uppercase">Design by them</span><br>
                                <a href="<?php echo $product->getProductUrl()?>" style="text-decoration: none"><span
                                            style="font-weight: 500; color: #5a5a5a"><?php echo $product->getName() ?></span></a><br>
                                <span><?php echo $currencySymbol . '' . $finalPriceAmt ?></span>
                            </div>
                            <div class="product-actions" style="width: 40%; float: right; text-align: right">
                                <div class="product-addtocart" style="display: inline-block; padding-right: 12px">
                                    <a href="#"><img src="<?php $block->getBaseUrl() ?>pub/media/wysiwyg/smartwave/porto/icon/icon-cart.png"
                                         alt="" style="width: 15px;"></a>
                                </div>
                                <div class="product-addtowishlist" style="display: inline-block">
                                    <a href="#"><img src="<?php $block->getBaseUrl() ?>pub/media/wysiwyg/smartwave/porto/icon/icon-heart.png"
                                         alt="" style="width: 15px"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
