<?php
/**
 * Edited for you list template
 *
 * @var $block \Smartwave\Filterproducts\Block\Home\FeaturedList
 */
$productCollection = $block->getLoadedProductCollection();
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$image = 'category_page_grid-hover';

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
$currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode);
$currencySymbol = $currency->getCurrencySymbol();
?>

<div class="row">
    <div class="col-lg-5">
        <div class="product-info col-lg-7">
            <p style="font-size: 20px; font-weight: 500; text-transform: uppercase; text-align: center; margin-bottom: 30px">
                Shop the look</p>
            <a class="prev" onclick="plusProduct(-1)">❮</a>
            <a class="next" onclick="plusProduct(1)">❯</a>
            <?php foreach ($productCollection as $product): ?>
                <?php $finalPriceAmt = $product->getPriceInfo()->getPrice('final_price')->getValue(); ?>
                <?php $imagePreview = $block->getUrl('pub/media') . 'catalog/product' . $product->getData('test') ?>
                <?php $imagePlaceholder = $block->getUrl('pub/media') . 'catalog/product/placeholder/default/default.jpg' ?>
                <?php $productImage = $_imagehelper->init($product, $image)->resize(340, 340); ?>
                <?php $productImageUrl = $productImage->getUrl() ?>
                <div class="product-item-block">
                    <div class="product-item-image">
                        <img src="<?php echo $productImageUrl ?>" style="width: 100%; height: 100%; background: #e5e5e5"
                             alt="">
                        <?php if ($product->getData('test') == NULL): ?>
                            <img src="<?php echo $imagePlaceholder ?>" alt="" class="image-url" style="display: none">
                        <?php else: ?>
                            <img src="<?php echo $imagePreview ?>" alt="" class="image-url" style="display: none">
                        <?php endif; ?>
                    </div>
                    <div class="product-item-detail">
                        <div class="product-text-info" style="width: 80%; float: left; line-height: 18px">
                            <span style="font-size: 10px; text-transform: uppercase">Design by them</span><br>
                            <a href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName(); ?></a><br>
                            <span><?php echo $currencySymbol . '' . $finalPriceAmt ?></span>
                        </div>
                        <a href="#"><img
                                    src="<?php $block->getBaseUrl() ?>pub/media/wysiwyg/smartwave/porto/icon/icon-heart.png"
                            alt="" style="float: right; width: 15px"></a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-lg-7" style="padding: 0">
        <div class="image-preview" style="height: 550px; width: 100%;">
            <img id="image-custom" src="" alt="" style="height: 100%; width: 100%;">
        </div>
    </div>
</div>
