<?php
/**
 * Category list template
 *
 * @var $block \Smartwave\Categories\Block\ListCategory
 */
?>

<div class="row" style="padding-bottom: 30px">
    <div class="col-lg-4">
        <div class="image-category">
            <a href="<?php echo $block->getCategoryUrl(14)?>"><img src="<?php echo $block->getCategoryImageUrl(14)?>" alt=""></a>
            <div class="title-category">
                <a href="<?php echo $block->getCategoryUrl(14)?>"><?php echo $block->getCategoryName(14)?></a>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="image-category">
            <a href="<?php echo $block->getCategoryUrl(16)?>"><img src="<?php echo $block->getCategoryImageUrl(16)?>" alt=""></a>
            <div class="title-category">
                <a href="<?php echo $block->getCategoryUrl(16)?>"><?php echo $block->getCategoryName(16)?></a>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="image-category">
            <a href="<?php echo $block->getCategoryUrl(17)?>"><img src="<?php echo $block->getCategoryImageUrl(17)?>" alt=""></a>
            <div class="title-category">
                <a href="<?php echo $block->getCategoryUrl(17)?>"><?php echo $block->getCategoryName(17)?></a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-3">
        <div class="image-category">
            <a href="<?php echo $block->getCategoryUrl(17)?>"><img src="<?php echo $block->getCategoryImageUrl(18)?>" alt=""></a>
            <div class="title-category">
                <a href="<?php echo $block->getCategoryUrl(17)?>"><?php echo $block->getCategoryName(18)?></a>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="image-category">
            <a href="<?php echo $block->getCategoryUrl(18)?>"><img src="<?php echo $block->getCategoryImageUrl(19)?>" alt=""></a>
            <div class="title-category">
                <a href="<?php echo $block->getCategoryUrl(18)?>"><?php echo $block->getCategoryName(19)?></a>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="image-category">
            <a href="<?php echo $block->getCategoryUrl(19)?>"><img src="<?php echo $block->getCategoryImageUrl(20)?>" alt=""></a>
            <div class="title-category">
                <a href="<?php echo $block->getCategoryUrl(19)?>"><?php echo $block->getCategoryName(20)?></a>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="image-category">
            <a href="<?php echo $block->getCategoryUrl(20)?>"><img src="<?php echo $block->getCategoryImageUrl(21)?>" alt=""></a>
            <div class="title-category">
                <a href="<?php echo $block->getCategoryUrl(20)?>"><?php echo $block->getCategoryName(21)?></a>
            </div>
        </div>
    </div>
</div>


